on:
  pull_request:
    branches: main

jobs:
  run-tests:
    runs-on: ubuntu-latest  
    name: Executar testes
    steps:
      - name: Baixar repositório e acessar branch
        uses: actions/checkout@v3

      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Executar testes
        run: mvn clean test
